# fly.toml app configuration file generated for fs-chaot on 2025-10-23T17:30:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fs-chaot'
primary_region = 'fra'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "db"
destination = "/usr/local/app/db"
